# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Haluk Barkın Evgin
title: Senior Software/Game Developer
email: barkin.evgin@gmail.com
#website: www.github.com/hbarkine/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  hbarkine
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: haluk-barkın-evgin-770907159
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/vesikalik.png
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm Haluk Barkin Evgin, a dedicated and passionate software engineer, always eager to learn and grow. My academic journey began at <mark>Middle East Technical University</mark>, where I majored in Electrical and Electronics Engineering. The final year of my study saw a strategic shift as I chose to specialize in Computer Science. This decision, fueled by my deep-rooted curiosity for software development, led me to be recognized with the Bulent Kerim Altay Academic Excellence Award for maintaining a perfect GPA during a semester.
  
  Even before completing my education, I started my professional journey with <mark>Aselsan</mark>, one of Turkey's leading defense companies, as a part-time software engineer. After graduation, I transitioned to a full-time role, remaining with <mark>Aselsan</mark> for <mark>4</mark> enriching years. During this time, I not only improved my skills and gained valuable experience in the defense industry but also simultaneously pursued a <mark>master's degree</mark> in Computer Science from <mark>Middle East Technical University</mark>, reaffirming my commitment to continuous learning and growth.
  
  Seeking a new challenge and driven by a desire to contribute to a dynamic and creative field, I made the move to <mark>Brew Games</mark>. For the past <mark>2</mark> years, as a part of the core team of game developers, I've been focused on refining my craft and pushing boundaries in the gaming industry. Leveraging my past experiences and continually exploring new territories in game development, I remain committed to making significant contributions to the ever-evolving tech industry.
  
  I hold strong expertise in <mark>Unity, C#, Python, and C++,</mark> forming the core of my technical skill set.

content:

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ASELSAN Inc. 
        link: aselsan.com/en
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: January 2017 - May 2021
        quote: >
          Established in 1975, ASELSAN Inc. is a leading Turkish company known for producing cutting-edge electronic systems and technologies for defense, security, traffic, and energy sectors.
        description: | # this will include new lines to allow paragraphs
          Main responsibility is developing software for radar simulators and flight simulations. 
          Major tasks are listed below:
          - Development of software for communications between SUT (System under Test) and System, using different communication protocols <mark>(TCP - UDP - RS232/422)</mark> and integrating these software to real time loops. These software are developed using <mark>C++</mark> on a real time <mark>Linux</mark> distribution. 
          - Developing Simulink models for spatial calculations and coordinate conversions for these simulations. Generating real time codes from these models and integrating these models to real time loop.
          - Verification and Testing of the abovementioned software using several arm based systems.
          - Development of software for various RF Radar System Simulators using <mark>C++</mark> and <mark>Python</mark>.
          - Developing Test and Validation software and GUIs using Visual <mark>C#</mark> on <mark>.Net</mark>.

      - layout: left
        title: Brew Games
        link: brew-games.com
        # link_text: boringcompany.com
        sub_title: Game/Software Developer
        caption: May 2021 - Present
        quote: >
          Established in 2021, Brew Games is an Innovative company that is specialized on developing games on Hybrid-Casual Genre.
        description: | # this will include new lines to allow paragraphs
          Main responsibility is developing Gameplay code for games that are being published. 
          Major tasks are listed below:
          - Development of games using <mark>Unity</mark> 3D and 2D using <mark>C#</mark> programming language 
          - Maintaining development tools that can be used to generate games in specific genres. 
          - Leading a team composed of developers and game artists.
          - Helping to the development of a SDK for the self publishing needs
          - Developing and maintaining <mark>CI</mark> (Continuous Integration) systems based of <mark>JENKINS</mark> for automatizing publishing and testing processes.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Middle East Technical University
        caption: 2012 - 2017
        sub_title: BSc Electrical and Electronics Engineering (Computer Science Option)
        quote: >
          Founded in 1956, Middle East Technical University is a prestigious public research university in Turkey, renowned for its rigorous engineering and natural sciences programs, and its commitment to innovation and interdisciplinary research.
        description: | # this will include new lines to allow paragraphs
          Throughout my Bachelor's Degree, I acquired a comprehensive understanding of the fundamental engineering concepts that would serve as the cornerstone for my ensuing professional journey. 

          I spent a lot of my free time as a committee member of METU Tennis society.

      - layout: left
        title: Middle East Technical University
        caption: 2017 - 2021
        sub_title: MSc Electrical and Electronics Engineering (Computer Science Option)
        quote: >
          Founded in 1956, Middle East Technical University is a prestigious public research university in Turkey, renowned for its rigorous engineering and natural sciences programs, and its commitment to innovation and interdisciplinary research.
        description: | # this will include new lines to allow paragraphs
          Throughout my Master's Degree, I delved into the utilization of Deep Learning in Biomedical applications. My academic contributions culminated in a scholarly publication focusing on the application of Deep Learning in a specialized area within the field. This research has been acknowledged by the academic community, accruing 13 official citations from the IEEE. The primary tool for the software development involved in this research was Python.

  - title: Game Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: |
          In my journey within the gaming industry, I've been fortunate to have many of my prototypes reach the soft launch stage, a testament to the high standard of my work. I wish to highlight <mark>5</mark> projects in my portfolio where I was either the sole developer or one of the key contributors driving the project forward. Projects where I played a peripheral or support role will not be included, as my focus is on showcasing the ones where my involvement was pivotal.
      - layout: top-middle
        title: Oil Tycoon Idle 3D
        link: https://apps.apple.com/us/app/oil-tycoon-idle-3d/id1621684059
        link_text: App Store Page
        additional_links:
          #  icon: fab fa-github
          link: https://drive.google.com/drive/folders/1Fs1jugwiXmJT8zdC0HhrYorysG9lIkDs?usp=sharing
          link_text: Videos
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          As the only developer for this project, which marked one of our company's initial soft launches with an external publisher, I take immense pride in the quality of the end product. Given my exclusive involvement in this project, I consider it a significant highlight in my portfolio, deserving of primary emphasis.  
  
      - layout: top-middle
        title: Clean Streets 3D
        link: https://apps.apple.com/id/app/clean-streets-3d/id1637077364
        link_text: App Store Page
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Although the marketibility of this game has not been very successful after the soft launch phase, as a team we are very proud with the quality of the </mark>physics<mark> control of the vehicle that we introduced to this game. As a tecnhical showcase I wanted to include this game in my portfolio.
          

      - layout: top-middle
        title: Color Slice Fun 3D
        link: https://apps.apple.com/us/app/color-slice-fun-3d/id6444259329
        link_text: App Store Page
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Despite the technical simplicity commonly associated with runner games, I aimed to enhance its marketability by introducing and developing <mark>vertex shaders</mark> for dynamic visual effects on various obstacles. The principal reason for including this project in my portfolio is to highlight this unique technical attribute. I strongly recommend experiencing this game on a device firsthand, as the marketing creatives may not fully encapsulate its features due to marketability considerations. 


      - layout: top-middle
        title: Horse Dreams Ride & Race!
        link: https://apps.apple.com/us/app/horse-dreams-ride-race/id6446779021
        link_text: App Store Page
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Though this game's development was halted after initial tests, I still consider it a significant part of my portfolio, as I was the sole developer on this prototype. As mobile developers, we consistently strive for marketable concepts, and while the theme of horses may not fit this criteria, the limited development time spent on this game serves as a testament to my rapid prototyping skills, which is why I'm keen on showcasing it. Also I am pretty satisfied with the horse riding mechanics.


      - layout: top-middle
        title: Wedding Planner - DIY!
        link: https://apps.apple.com/us/app/wedding-planner-diy/id6446688300
        link_text: App Store Page
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          In the development cycle of this game, my main responsibility was to develop and maintain upgrade and <mark>UI</mark> systems. So in order to showcase my UI programming abilities, I wanted to include this game in my portfolio.
          



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
